title: QuinceTart10's blog
description: A small blog written by QuinceTart10
logo: /assets/pfp.png
google_site_verification: XFGrFJ2fqBhNcjcwKyouwLk7209QxI94SDqjUn2D5Ug
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/pfp.png
  - scope:
      path: "googlef43f6ccad8783b2f.html"
    values:
      sitemap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag